---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - namespace-secrets-patcher.infrabits.nl
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - namespace-secrets-patcher.infrabits.nl
  resources:
  - patchers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - namespace-secrets-patcher.infrabits.nl
  resources:
  - patchers/finalizers
  verbs:
  - update
- apiGroups:
  - namespace-secrets-patcher.infrabits.nl
  resources:
  - patchers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - namespace-secrets-patcher.infrabits.nl
  resources:
  - secrets
  verbs:
  - create
  - get
  - update
  - watch
