apiVersion: namespace-secrets-patcher.infrabits.nl/v1
kind: Patcher
metadata:
  labels:
    app.kubernetes.io/name: namespace-secrets-patcher
    app.kubernetes.io/managed-by: kustomize
  name: example-patcher
  namespace: kube-system
spec:
  secret: ghcr
  targets:
    - name: default
      type: match
    - name: internal-
      type: prefix
