apiVersion: namespace-secrets-patcher.infrabits.nl/v1
kind: Patcher
metadata:
  labels:
    app.kubernetes.io/name: namespace-secrets-patcher
    app.kubernetes.io/managed-by: kustomize
  name: patcher-sample
spec:
  # TODO(user): Add fields here
